"""
Telara Biometric Event Schemas
Standardized data models for IoT device simulation.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import List, Optional
from enum import Enum
import uuid


class Posture(str, Enum):
    LYING = "lying"
    SEATED = "seated"
    STANDING = "standing"
    WALKING = "walking"
    RUNNING = "running"


class SleepStage(str, Enum):
    AWAKE = "awake"
    LIGHT = "light"
    DEEP = "deep"
    REM = "rem"


class DeviceSource(str, Enum):
    APPLE_WATCH = "apple_watch"
    OURA_RING = "oura_ring"
    WITHINGS_SCALE = "withings_scale"
    FITBIT = "fitbit"
    GARMIN = "garmin"
    DEXCOM_CGM = "dexcom_cgm"
    OMRON_BP = "omron_bp"


@dataclass
class Vitals:
    """Core vital signs from wearables."""
    heart_rate: int  # bpm (60-200)
    hrv_ms: int  # Heart Rate Variability in ms (20-100)
    spo2_percent: int  # Blood oxygen (90-100)
    skin_temp_c: float  # Skin temperature (35.0-40.0)
    respiratory_rate: int  # Breaths per minute (12-25)
    blood_pressure_systolic: Optional[int] = None  # (90-180)
    blood_pressure_diastolic: Optional[int] = None  # (60-120)


@dataclass
class Activity:
    """Activity and movement metrics."""
    steps_per_minute: int  # (0-200)
    activity_level: int  # 0-100 scale
    calories_per_minute: float  # (0.5-20)
    posture: str  # Posture enum value


@dataclass
class Sleep:
    """Sleep-related metrics."""
    stage: Optional[str]  # SleepStage enum value or None
    hours_last_night: float  # (4-10)


@dataclass
class Environment:
    """Environmental sensor data."""
    room_temp_c: float  # (15-30)
    humidity_percent: int  # (20-80)


@dataclass
class BiometricEvent:
    """
    Unified biometric event schema.
    Aggregates data from multiple IoT device sources.
    """
    event_id: str
    timestamp: str
    user_id: str
    device_sources: List[str]
    vitals: Vitals
    activity: Activity
    sleep: Sleep
    environment: Environment
    
    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp,
            "user_id": self.user_id,
            "device_sources": self.device_sources,
            "vitals": asdict(self.vitals),
            "activity": asdict(self.activity),
            "sleep": asdict(self.sleep),
            "environment": asdict(self.environment),
        }
    
    def to_flat_dict(self) -> dict:
        """
        Convert to flattened dictionary for Flink SQL processing.
        This format is easier to query with Flink SQL.
        """
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp,
            "user_id": self.user_id,
            "device_sources": self.device_sources,
            # Vitals (flattened)
            "heart_rate": self.vitals.heart_rate,
            "hrv_ms": self.vitals.hrv_ms,
            "spo2_percent": self.vitals.spo2_percent,
            "skin_temp_c": self.vitals.skin_temp_c,
            "respiratory_rate": self.vitals.respiratory_rate,
            "blood_pressure_systolic": self.vitals.blood_pressure_systolic,
            "blood_pressure_diastolic": self.vitals.blood_pressure_diastolic,
            # Activity (flattened)
            "steps_per_minute": self.activity.steps_per_minute,
            "activity_level": self.activity.activity_level,
            "calories_per_minute": self.activity.calories_per_minute,
            "posture": self.activity.posture,
            # Sleep (flattened)
            "sleep_stage": self.sleep.stage,
            "hours_last_night": self.sleep.hours_last_night,
            # Environment (flattened)
            "room_temp_c": self.environment.room_temp_c,
            "humidity_percent": self.environment.humidity_percent,
        }


@dataclass
class AlertEvent:
    """Schema for anomaly alerts generated by Flink."""
    alert_id: str
    alert_type: str
    user_id: str
    severity: str  # CRITICAL, HIGH, MEDIUM, LOW
    start_time: str
    end_time: str
    avg_heart_rate: float
    event_count: int
    description: str
    
    def to_dict(self) -> dict:
        return asdict(self)


# Baseline ranges for normal vital signs
NORMAL_RANGES = {
    "heart_rate": (60, 80),
    "hrv_ms": (40, 70),
    "spo2_percent": (96, 100),
    "skin_temp_c": (36.0, 37.0),
    "respiratory_rate": (12, 18),
    "blood_pressure_systolic": (110, 130),
    "blood_pressure_diastolic": (70, 85),
    "steps_per_minute": (0, 5),  # At rest
    "activity_level": (0, 15),  # Sedentary
    "room_temp_c": (20, 24),
    "humidity_percent": (40, 60),
}

# Anomaly patterns for injection
ANOMALY_PATTERNS = {
    "tachycardia_at_rest": {
        "heart_rate": (110, 140),
        "activity_level": (0, 8),
        "steps_per_minute": (0, 3),
        "hrv_ms": (20, 35),  # Lower HRV during stress
    },
    "hypoxia": {
        "spo2_percent": (88, 93),
        "respiratory_rate": (20, 28),
        "heart_rate": (85, 105),
    },
    "fever_onset": {
        "skin_temp_c": (37.8, 39.5),
        "heart_rate": (90, 110),
        "hrv_ms": (25, 40),
    },
    "burnout_stress": {
        "hrv_ms": (15, 30),
        "heart_rate": (85, 100),
        "sleep_hours": (4, 5.5),
    },
    "dehydration": {
        "heart_rate": (90, 110),
        "blood_pressure_systolic": (95, 110),
        "skin_temp_c": (37.0, 37.5),
    },
}

